/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author magne
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        //Sirve para que la ventana aparezca en el centro.
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnColegio = new javax.swing.JButton();
        btnAlumno = new javax.swing.JButton();
        btnProfesor = new javax.swing.JButton();
        btnMateria = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(650, 450));
        setMinimumSize(new java.awt.Dimension(650, 450));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        btnColegio.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        btnColegio.setText("Colegio");
        btnColegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColegioActionPerformed(evt);
            }
        });
        getContentPane().add(btnColegio);
        btnColegio.setBounds(400, 120, 160, 80);

        btnAlumno.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        btnAlumno.setText("Alumno");
        btnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumno);
        btnAlumno.setBounds(240, 200, 160, 80);

        btnProfesor.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        btnProfesor.setText("Profesor");
        btnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfesor);
        btnProfesor.setBounds(400, 280, 160, 80);

        btnMateria.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        btnMateria.setText("Materia");
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMateria);
        btnMateria.setBounds(80, 120, 160, 80);

        btnRegistro.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistro);
        btnRegistro.setBounds(80, 280, 160, 80);

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SOTFWARE ESTUDIANTIL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 620, 90);

        lblImagenFondo.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        lblImagenFondo.setForeground(new java.awt.Color(0, 0, 0));
        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/writing-1149962_640.png"))); // NOI18N
        lblImagenFondo.setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().add(lblImagenFondo);
        lblImagenFondo.setBounds(0, 0, 660, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoActionPerformed
        Alumno alumno = new Alumno();
        alumno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAlumnoActionPerformed

    private void btnColegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColegioActionPerformed
        Colegio colegio = new Colegio();
        colegio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnColegioActionPerformed

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        Materia materia = new Materia();
        materia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorActionPerformed
        Profesor profesor = new Profesor();
        profesor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProfesorActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        Registro registro = new Registro();
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnColegio;
    private javax.swing.JButton btnMateria;
    private javax.swing.JButton btnProfesor;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImagenFondo;
    // End of variables declaration//GEN-END:variables
}
