package Vistas;

import ComboBox.InformacionColegio;
import ProgramacionTablas.*;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Johan Sebastian Lasso Rivas y Juan Sebastian
 */
public class Profesor extends javax.swing.JFrame {

    //Variables Globales
    private DefaultTableModel modelo;
    //almacena el indice (fila) del JTable.
    public int indiceFila; 
    
    
    public Profesor() {
        initComponents();
        //Sirve para que la ventana aparezca en el centro.
        this.setLocationRelativeTo(null);
        
        InformacionColegio infColegio = new InformacionColegio();
        
        //Creamos un Objeto para obtener el modelo del comboBox
        DefaultComboBoxModel objColegio = new DefaultComboBoxModel(infColegio.mostrarColegio());
        cmbColegio.setModel(objColegio);
        txtIdProfesor.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdProfesor = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        txtIdProfesor = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        lblCedulaProfesional = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfesor = new javax.swing.JTable();
        txtCedulaProfesional = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblColegio = new javax.swing.JLabel();
        cmbColegio = new javax.swing.JComboBox<>();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(851, 450));
        setUndecorated(true);
        setResizable(false);

        lblIdProfesor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIdProfesor.setText("Profesor:");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellidoPaterno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblApellidoPaterno.setText("Apellido Paterno:");

        lblApellidoMaterno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblApellidoMaterno.setText("Apellido Materno:");

        txtIdProfesor.setBackground(new java.awt.Color(102, 102, 102));
        txtIdProfesor.setForeground(new java.awt.Color(255, 255, 255));
        txtIdProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProfesorActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(102, 102, 102));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));

        txtApellidoPaterno.setBackground(new java.awt.Color(102, 102, 102));
        txtApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));

        txtApellidoMaterno.setBackground(new java.awt.Color(102, 102, 102));
        txtApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoActionPerformed(evt);
            }
        });

        lblCedulaProfesional.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCedulaProfesional.setText("Cedula Profesional:");

        lblDireccion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDireccion.setText("Direccion:");

        tblProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProfesorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProfesor);

        txtCedulaProfesional.setBackground(new java.awt.Color(102, 102, 102));
        txtCedulaProfesional.setForeground(new java.awt.Color(255, 255, 255));

        txtDireccion.setBackground(new java.awt.Color(102, 102, 102));
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PROFESOR");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblColegio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblColegio.setText("Colegio:");

        cmbColegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "***Selecciona***" }));

        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home-icon-silhouette.png"))); // NOI18N
        btnInicio.setBorderPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblColegio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbColegio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblIdProfesor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProfesor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCedulaProfesional)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedulaProfesional))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblApellidoMaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoMaterno))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblApellidoPaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInicio)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGuardar)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEliminar)
                                .addComponent(btnLimpiar)
                                .addComponent(btnActualizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdProfesor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColegio)
                            .addComponent(cmbColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoPaterno)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoMaterno)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedulaProfesional)
                            .addComponent(txtCedulaProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDireccion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProfesorActionPerformed

    private void txtApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        //Validación de cada una de las cajas de Texto (Campos vacios).

        
        if(cmbColegio.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(null, "Por favor,digita el nombre del Colegio" );
            cmbColegio.requestFocus();
            return;
        }
        
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el nombre del Profesor" );
            txtNombre.requestFocus();
            return;
        }
        
        if(txtApellidoPaterno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el apellido paterno" );
            txtApellidoPaterno.requestFocus();
            return;
        }
        if(txtApellidoMaterno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el apellido materno" );
            txtApellidoMaterno.requestFocus();
            return;
        }
        
        if(txtApellidoMaterno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el apellido materno" );
            txtApellidoMaterno.requestFocus();
            return;
        }
        
        if(txtCedulaProfesional.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita la cedula" );
            txtCedulaProfesional.requestFocus();
            return;
        }
        if(txtDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita la direccion" );
            txtDireccion.requestFocus();
            return;
        }


        TablaProfesor  objProfesor = new TablaProfesor();
        
        InformacionColegio objColegio = (InformacionColegio) cmbColegio.getSelectedItem();

        //Declaración de las variables para obtener los valores que se encuentran en las cajas de texto
        int idColegio = objColegio.getId();
        String nombre = txtNombre.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        int cedula = Integer.parseInt(txtCedulaProfesional.getText());
        String direccion = txtDireccion.getText();
        
        

        try {
            boolean resultado = objProfesor.insertarProfesor(idColegio, nombre, apellidoPaterno, apellidoMaterno, cedula, direccion);
            if(resultado == true){
                JOptionPane.showMessageDialog(null, "Se inserto un nuevo registro.");
                //Utilizamos el objeto para limpiar todos los campos.
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al insertar.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lo sentimos, ocurrió algo inesperado. ¡Por favor, vuelva a intentarlo!");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
        limpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiarTabla();
        getColumn();
        cargarTabla();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         //Saber si la tabla esta vacia esto me permite decirle al Usuario que presione el boton de buscar registros.
        
        txtIdProfesor.setEditable(false);
        
        if(tblProfesor.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Por favor, Presione el botón de Bucar" );
            return;
        }

        if (tblProfesor.getSelectedRow()== -1) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila");
            return;
        }
        
        // Defino el modelo para el JTable
        modelo = (DefaultTableModel) tblProfesor.getModel();
        
        TablaProfesor objProfesor = new TablaProfesor();
        
        try {
             
            // Asigno el indice del elemento seleccionado
            indiceFila = tblProfesor.getSelectedRow();
            // Elimino el registro del JTable
            modelo.removeRow(indiceFila);
   
            
            //Declaración de la vaiable para obtener el valor que se encuentra en la caja de texto correspondiente.
            int idProfesor = Integer.parseInt(txtIdProfesor.getText());
            boolean resultado = objProfesor.eliminarProfesor(idProfesor);
            if (resultado == true) {
                JOptionPane.showMessageDialog(null, "Se Eliminó el registro correctamente.");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al Eliminar.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lo sentimos, ocurrió algo inesperado ¡Por favor, vuelva a intentarlo!" + e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProfesorMouseClicked
        /* Evento para cuendo el usuario presione click en cualquier fila de la tabla. 
           Lo que hará ese evento es poner todo los datos que hayan en la tabla en los distintos.
           JtextFiel , JCombobox.
        */
        //Modelo para el JTable
        modelo = (DefaultTableModel) tblProfesor.getModel();

        // Asigno el elemento seleccionado de la tabla a los respectivos campos del formulario
        try {
            //Deshabilitar el campo de Codigo
            txtIdProfesor.setEditable(false);
            
            InformacionColegio objClegio = new InformacionColegio();
            

            //Realizamos una Instanciación para el modelo del comboBox perteneciente a los Departamentos. 
            DefaultComboBoxModel modeloColegio = new DefaultComboBoxModel(objClegio.mostrarColegio());
            
            txtIdProfesor.setText(String.valueOf(modelo.getValueAt(tblProfesor.getSelectedRow(), 0)));
            
            String colegio = (String) modelo.getValueAt(tblProfesor.getSelectedRow(), 1);
            modeloColegio.setSelectedItem(colegio);
            cmbColegio.setModel(modeloColegio);
            
            
            txtNombre.setText((String)(modelo.getValueAt(tblProfesor.getSelectedRow(), 2)));
            txtApellidoPaterno.setText((String) modelo.getValueAt(tblProfesor.getSelectedRow(), 3));
            txtApellidoMaterno.setText((String) modelo.getValueAt(tblProfesor.getSelectedRow(), 4));
            txtCedulaProfesional.setText(String.valueOf(modelo.getValueAt(tblProfesor.getSelectedRow(), 5)));
            txtDireccion.setText((String) modelo.getValueAt(tblProfesor.getSelectedRow(), 6));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lo sentimos, ocurrió algo inesperado al momento de seleccionar una fila ¡Por favor, vuelva a intentarlo!");
        }
    }//GEN-LAST:event_tblProfesorMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //Validación de cada una de las cajas de Texto (Campos vacios).
        
        txtIdProfesor.setEditable(false);
        
        if(cmbColegio.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(null, "Por favor,digita el nombre del Colegio" );
            cmbColegio.requestFocus();
            return;
        }
        
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el nombre del Profesor" );
            txtNombre.requestFocus();
            return;
        }
        
        if(txtApellidoPaterno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el apellido paterno" );
            txtApellidoPaterno.requestFocus();
            return;
        }
        if(txtApellidoMaterno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el apellido materno" );
            txtApellidoMaterno.requestFocus();
            return;
        }
        
        if(txtApellidoMaterno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita el apellido materno" );
            txtApellidoMaterno.requestFocus();
            return;
        }
        
        if(txtCedulaProfesional.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita la cedula" );
            txtCedulaProfesional.requestFocus();
            return;
        }
        if(txtDireccion.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor,digita la direccion" );
            txtDireccion.requestFocus();
            return;
        }
        
        
        
        TablaProfesor  objProfesor = new TablaProfesor();
        
        InformacionColegio objColegio = (InformacionColegio) cmbColegio.getSelectedItem();
       
        //Declaración de las variables para obtener los valores que se encuentran en las cajas de texto
        int idProfesor = Integer.parseInt(txtIdProfesor.getText());
        int idColegio = objColegio.getId();
        String nombre = txtNombre.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        int cedula = Integer.parseInt(txtCedulaProfesional.getText());
        String direccion = txtDireccion.getText();
        
        boolean resultado = objProfesor.actualizarProfesor(idProfesor, idColegio, nombre, apellidoPaterno, apellidoMaterno,cedula,direccion);
        if(resultado == true){
            JOptionPane.showMessageDialog(null, "Se actualizó el registro.");
            //Se realiza la limpieza al JTable
            limpiarCampos();
            //Se realiza la liempieza a los TexField, ComboBox etc.
            limpiarTabla();
            //Mostramos las columnas (La informacion que identifica a cada tabla en la BD)
            getColumn();
            //Actualizamos la tabla (Buscamos todos los registros)
            cargarTabla();
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar.");
        }  
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void limpiarCampos(){
        txtIdProfesor.setText("");
        cmbColegio.setSelectedIndex(0);
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtCedulaProfesional.setText("");
        txtDireccion.setText("");
        txtIdProfesor.setEditable(true);
    }
    private void limpiarTabla(){
        // Defino el modelo para el JTable
        DefaultTableModel modelo = (DefaultTableModel) tblProfesor.getModel();
        
        // Limpio las filas y las columnas de la tabla
        modelo.setColumnCount(0);
        modelo.setNumRows(0);
    }
    
    
    //Metodo para cargar las columnas en la tabla
    private void getColumn() {
        modelo = (DefaultTableModel) tblProfesor.getModel();
        // Cargo las columnas de titulo al Jtable
        modelo.addColumn("ID");
        modelo.addColumn("Colegio");
        modelo.addColumn("nombre");
        modelo.addColumn("Apell. Paterno");
        modelo.addColumn("Apell. Materno");
        modelo.addColumn("Cedula");
        modelo.addColumn("Direccion");
    }
    
    //Metodo para cargar los registros en la tabla
    private void cargarTabla() {
        TablaProfesor objProfesor = new TablaProfesor();
        //Se Identifica el modelo de la JTable
        modelo = (DefaultTableModel) tblProfesor.getModel();
        ResultSet resultado = objProfesor.cargarInfoProfesor();
        try {
            Object datos[] = new Object[7];
            while (resultado.next()) {
                for (int i = 0; i < 7; i++) {
                    //Importante, el getObject tiene que ser mayor que 0 por ende se coloca el 1
                    datos[i] = resultado.getObject(i + 1);
                }
                modelo.addRow(datos);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbColegio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblCedulaProfesional;
    private javax.swing.JLabel lblColegio;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIdProfesor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblProfesor;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCedulaProfesional;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdProfesor;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
