package LDI.Colegios;


/**
* Colegios/Colegio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Colegio.idl
* domingo 12 de mayo de 2019 04H05' COT
*/

public interface Colegio extends ColegioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Colegio
