package Profesores;

/**
* Profesores/ProfesorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Profesor.idl
* domingo 19 de mayo de 2019 11:20:59 PM COT
*/

public final class ProfesorHolder implements org.omg.CORBA.portable.Streamable
{
  public Profesores.Profesor value = null;

  public ProfesorHolder ()
  {
  }

  public ProfesorHolder (Profesores.Profesor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Profesores.ProfesorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Profesores.ProfesorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Profesores.ProfesorHelper.type ();
  }

}
