package Profesores;


/**
* Profesores/ProfesorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Profesor.idl
* domingo 19 de mayo de 2019 11:20:59 PM COT
*/

public interface ProfesorOperations 
{
  boolean insertarProfesor (int idColegio, String nombre, String apellidoPaterno, String apellidoMaterno, int cedula, String direccion);
  boolean actualizarProfesor (int idProfesor, int idColegio, String nombre, String apellidoPaterno, String apellidoMaterno, int cedula, String direccion);
  boolean eliminarProfesor (int idProfesor);
  String consultarProfesor (int idProfesor);
  void shutdown ();
} // interface ProfesorOperations
