package Colegios;


/**
* Colegios/ColegioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Colegio.idl
* domingo 12 de mayo de 2019 04H05' COT
*/

public interface ColegioOperations 
{
  boolean insertarColegio (int idColegio, String nombre, String direccion, String telefono, String correo);
  boolean actualizarColegio (int idColegio, String nombre, String direccion, String telefono, String correo);
  boolean eliminarColegio (int idColegio);
  String consultarColegio (int idColegio);
  void shutdown ();
} // interface ColegioOperations
