package Colegios;

/**
* Colegios/ColegioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Colegio.idl
* domingo 12 de mayo de 2019 04H05' COT
*/

public final class ColegioHolder implements org.omg.CORBA.portable.Streamable
{
  public Colegios.Colegio value = null;

  public ColegioHolder ()
  {
  }

  public ColegioHolder (Colegios.Colegio initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Colegios.ColegioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        Colegios.ColegioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Colegios.ColegioHelper.type ();
  }

}
