package Materias;


/**
* Materias/MateriaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Materia.idl
* lunes 20 de mayo de 2019 10:19:16 AM COT
*/

public interface MateriaOperations 
{
  boolean insertarMateria (int idMateria, String nombre, String horario, String salon, int idProfesor);
  boolean actualizarMateria (int idMateria, String nombre, String horario, String salon, int idProfesor);
  boolean eliminarMateria (int idMateria);
  String consultarMateria (int idMateria);
  void shutdown ();
} // interface MateriaOperations
