package Materias;


/**
* Materias/Materia.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Materia.idl
* lunes 20 de mayo de 2019 10:19:16 AM COT
*/

public interface Materia extends MateriaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Materia
