package Materias;

/**
* Materias/MateriaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Materia.idl
* lunes 20 de mayo de 2019 10:19:16 AM COT
*/

public final class MateriaHolder implements org.omg.CORBA.portable.Streamable
{
  public Materias.Materia value = null;

  public MateriaHolder ()
  {
  }

  public MateriaHolder (Materias.Materia initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Materias.MateriaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Materias.MateriaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Materias.MateriaHelper.type ();
  }

}
