package Materias;


/**
* Materias/MateriaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Materia.idl
* lunes 20 de mayo de 2019 10:19:16 AM COT
*/

abstract public class MateriaHelper
{
  private static String  _id = "IDL:Materias/Materia:1.0";

  public static void insert (org.omg.CORBA.Any a, Materias.Materia that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Materias.Materia extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Materias.MateriaHelper.id (), "Materia");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Materias.Materia read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MateriaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Materias.Materia value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Materias.Materia narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Materias.Materia)
      return (Materias.Materia)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Materias._MateriaStub stub = new Materias._MateriaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Materias.Materia unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Materias.Materia)
      return (Materias.Materia)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Materias._MateriaStub stub = new Materias._MateriaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
