package Registros;


/**
* Registros/RegistroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* mircoles 22 de mayo de 2019 03:20:44 PM COT
*/

public interface RegistroOperations 
{
  boolean insertarRegistro (int idAlumno, int idMateria, int idProfesor);
  boolean actualizarRegistro (int id, int idAlumno, int idMateria, int idProfesor);
  boolean eliminarRegistro (int id);
  String consultarRegistro (int id);
  void shutdown ();
} // interface RegistroOperations
