package Registros;

/**
* Registros/RegistroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* mircoles 22 de mayo de 2019 03:20:44 PM COT
*/

public final class RegistroHolder implements org.omg.CORBA.portable.Streamable
{
  public Registros.Registro value = null;

  public RegistroHolder ()
  {
  }

  public RegistroHolder (Registros.Registro initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Registros.RegistroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Registros.RegistroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Registros.RegistroHelper.type ();
  }

}
