package Registros;


/**
* Registros/RegistroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* mircoles 22 de mayo de 2019 03:20:44 PM COT
*/

abstract public class RegistroHelper
{
  private static String  _id = "IDL:Registros/Registro:1.0";

  public static void insert (org.omg.CORBA.Any a, Registros.Registro that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Registros.Registro extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Registros.RegistroHelper.id (), "Registro");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Registros.Registro read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RegistroStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Registros.Registro value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Registros.Registro narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Registros.Registro)
      return (Registros.Registro)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Registros._RegistroStub stub = new Registros._RegistroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Registros.Registro unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Registros.Registro)
      return (Registros.Registro)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Registros._RegistroStub stub = new Registros._RegistroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
