package Registros;


/**
* Registros/Registro.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* mircoles 22 de mayo de 2019 03:20:44 PM COT
*/

public interface Registro extends RegistroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Registro
