package Registros;


/**
* Registros/RegistroPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Registro.idl
* mircoles 22 de mayo de 2019 03:20:44 PM COT
*/

public abstract class RegistroPOA extends org.omg.PortableServer.Servant
 implements Registros.RegistroOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarRegistro", new java.lang.Integer (0));
    _methods.put ("actualizarRegistro", new java.lang.Integer (1));
    _methods.put ("eliminarRegistro", new java.lang.Integer (2));
    _methods.put ("consultarRegistro", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Registros/Registro/insertarRegistro
       {
         int idAlumno = in.read_long ();
         int idMateria = in.read_long ();
         int idProfesor = in.read_long ();
         boolean $result = false;
         $result = this.insertarRegistro (idAlumno, idMateria, idProfesor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Registros/Registro/actualizarRegistro
       {
         int id = in.read_long ();
         int idAlumno = in.read_long ();
         int idMateria = in.read_long ();
         int idProfesor = in.read_long ();
         boolean $result = false;
         $result = this.actualizarRegistro (id, idAlumno, idMateria, idProfesor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Registros/Registro/eliminarRegistro
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarRegistro (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Registros/Registro/consultarRegistro
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarRegistro (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Registros/Registro/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Registros/Registro:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Registro _this() 
  {
    return RegistroHelper.narrow(
    super._this_object());
  }

  public Registro _this(org.omg.CORBA.ORB orb) 
  {
    return RegistroHelper.narrow(
    super._this_object(orb));
  }


} // class RegistroPOA
