package Alumnos;


/**
* Alumnos/_AlumnoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alumno.idl
* lunes 20 de mayo de 2019 09:29:56 AM COT
*/

public class _AlumnoStub extends org.omg.CORBA.portable.ObjectImpl implements Alumnos.Alumno
{

  public boolean insertarAlumno (int idAlumno, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, String telefono, String fechaIngreso)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarAlumno", true);
                $out.write_long (idAlumno);
                $out.write_wstring (nombre);
                $out.write_wstring (apellidoPaterno);
                $out.write_wstring (apellidoMaterno);
                $out.write_wstring (direccion);
                $out.write_wstring (telefono);
                $out.write_wstring (fechaIngreso);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarAlumno (idAlumno, nombre, apellidoPaterno, apellidoMaterno, direccion, telefono, fechaIngreso        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarAlumno

  public boolean actualizarAlumno (int idAlumno, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, String telefono, String fechaIngreso)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarAlumno", true);
                $out.write_long (idAlumno);
                $out.write_wstring (nombre);
                $out.write_wstring (apellidoPaterno);
                $out.write_wstring (apellidoMaterno);
                $out.write_wstring (direccion);
                $out.write_wstring (telefono);
                $out.write_wstring (fechaIngreso);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarAlumno (idAlumno, nombre, apellidoPaterno, apellidoMaterno, direccion, telefono, fechaIngreso        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarAlumno

  public boolean eliminarAlumno (int idAlumno)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarAlumno", true);
                $out.write_long (idAlumno);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarAlumno (idAlumno        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarAlumno

  public String consultarAlumno (int idAlumno)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarAlumno", true);
                $out.write_long (idAlumno);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarAlumno (idAlumno        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarAlumno

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Alumnos/Alumno:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AlumnoStub
