package Alumnos;


/**
* Alumnos/AlumnoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alumno.idl
* lunes 20 de mayo de 2019 09:29:56 AM COT
*/

public interface AlumnoOperations 
{
  boolean insertarAlumno (int idAlumno, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, String telefono, String fechaIngreso);
  boolean actualizarAlumno (int idAlumno, String nombre, String apellidoPaterno, String apellidoMaterno, String direccion, String telefono, String fechaIngreso);
  boolean eliminarAlumno (int idAlumno);
  String consultarAlumno (int idAlumno);
  void shutdown ();
} // interface AlumnoOperations
