package Alumnos;


/**
* Alumnos/Alumno.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Alumno.idl
* lunes 20 de mayo de 2019 09:29:56 AM COT
*/

public interface Alumno extends AlumnoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Alumno
